# This is a basic workflow to help you get started with Actions

name: Make Puzzle

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Make puzzle
        run: python tools/make_puzzle.py -c tools/corpuses/glypoon.txt -o public/puzzle/puzzle.json

      - name: Commit puzzle
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/puzzle/puzzle.json
          git commit -m "Generate puzzle for `date +%F`"
          git push
